/* ============================================================
   StartupAdvisorLM — frontend logic
   Talks to the FastAPI backend and draws all charts by hand
   (inline SVG + HTML bars) so there are zero chart-lib deps.
   ============================================================ */

const $ = (id) => document.getElementById(id);
const INK = "#141414";
const SEG_COLORS = ["#7dd3fc", "#f9a8d4", "#86efac", "#fdba74", "#c4b5fd"];

let SEGMENTS = null;

// ---- slider value labels -------------------------------------------------
const bind = (slider, out) => {
  const s = $(slider), o = $(out);
  s.addEventListener("input", () => (o.textContent = s.value));
};
bind("team", "team_val");
bind("fund", "fund_val");
bind("mkt", "mkt_val");

// ---- load segment scatter data once --------------------------------------
fetch("/segments").then((r) => r.json()).then((d) => (SEGMENTS = d)).catch(() => {});

// ---- Smart Mode availability ---------------------------------------------
fetch("/smart_status").then((r) => r.json()).then((s) => {
  const note = $("smart_note");
  if (s.available) {
    note.textContent = s.model || "";
  } else {
    $("smart").checked = false;
    $("smart").disabled = true;
    $("smart_toggle_row").classList.add("disabled");
    note.textContent = "unavailable";
    $("smart_toggle_row").title = s.reason || "Smart Mode unavailable";
  }
}).catch(() => {});

// ---- validate ------------------------------------------------------------
$("go").addEventListener("click", async () => {
  const idea = $("idea").value.trim();
  if (idea.length < 8) {
    alert("Please describe your idea in a sentence or two.");
    return;
  }
  const payload = {
    idea,
    team_size: +$("team").value,
    funding_k: +$("fund").value,
    market_size: +$("mkt").value,
  };
  const btn = $("go");
  btn.disabled = true;
  btn.textContent = "CRUNCHING…";
  try {
    const res = await fetch("/validate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    const r = await res.json();
    render(r);
    if ($("smart").checked) runAdvisor(payload);
    else $("smart_section").classList.add("hidden");
  } catch (e) {
    alert("Could not reach the server. Is the API running?");
  } finally {
    btn.disabled = false;
    btn.textContent = "VALIDATE IDEA →";
  }
});

// ---- Smart Mode: LLM-written advice --------------------------------------
async function runAdvisor(payload) {
  $("smart_section").classList.remove("hidden");
  $("smart_body").innerHTML =
    '<div class="smart-loading">🧠 Asking the advisor… (a few seconds)</div>';
  try {
    const res = await fetch("/advise", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    const a = await res.json();
    renderAdvice(a);
  } catch (e) {
    $("smart_body").innerHTML =
      '<div class="smart-err">Could not reach the advisor.</div>';
  }
}

function renderAdvice(a) {
  if (!a.available) {
    $("smart_body").innerHTML =
      `<div class="smart-err">Smart Mode is unavailable: ${escapeHtml(a.reason || "unknown error")}` +
      `<br><br>Set a valid <code>ANTHROPIC_API_KEY</code> and try again — the classical report above still stands.</div>`;
    return;
  }
  const list = (arr) => (arr || []).map((x) => `<li>${escapeHtml(x)}</li>`).join("");
  $("smart_body").innerHTML =
    `<div class="smart-oneliner">${escapeHtml(a.one_liner || "")}</div>` +
    `<div class="smart-take">${escapeHtml(a.verdict_take || "")}</div>` +
    `<div class="smart-grid">
       <div class="smart-col"><h4>💪 Strengths</h4><ul>${list(a.strengths)}</ul></div>
       <div class="smart-col"><h4>⚠️ Risks</h4><ul>${list(a.risks)}</ul></div>
       <div class="smart-col"><h4>✅ Do next</h4><ul>${list(a.suggestions)}</ul></div>
     </div>` +
    `<div class="smart-extra">
       <div><b>Ideal customer</b><br>${escapeHtml(a.ideal_customer || "")}</div>
       <div><b>Go-to-market</b><ul style="margin:.4rem 0 0">${list(a.gtm)}</ul></div>
       <div><b>Category note</b><br>${escapeHtml(a.category_note || "")}</div>
     </div>` +
    `<div class="smart-muted">Advice generated by ${escapeHtml(a.model || "Claude")} · scores above are from the classical ML pipeline.</div>`;
}

// ---- render report -------------------------------------------------------
function render(r) {
  $("results").classList.remove("hidden");

  // verdict
  const v = $("verdict");
  v.className = "card verdict " + r.verdict.toLowerCase();
  animateNumber($("v_num"), r.score);
  $("v_label").textContent = r.verdict;
  $("v_reason").textContent = r.reason;

  // stat blocks — category with a low-confidence guard
  const conf = r.confidence;
  const sub = $("s_cat_sub");
  if (conf < 0.40) {
    const second = topN(r.proba, 2)[1];
    $("s_cat").textContent = r.category + " ?";
    sub.innerHTML = `⚠ unsure (${Math.round(conf * 100)}%)` +
      (second ? ` — or <b>${escapeHtml(second[0])}</b>` : "");
  } else {
    $("s_cat").textContent = r.category;
    sub.textContent = Math.round(conf * 100) + "% confident";
  }
  $("s_succ").textContent = Math.round(r.success_prob * 100) + "%";
  $("s_sent").textContent = Math.round(r.sentiment_pos * 100) + "%";
  $("s_sent_sub").textContent = "positive · " + r.sentiment_reviews + " reviews";
  $("s_nov").textContent = Math.round(r.axes.Novelty) + "/100";

  // keyword chips
  $("chips").innerHTML = (r.keywords || [])
    .map((k) => `<span class="chip">🔑 ${escapeHtml(k)}</span>`).join("");

  // charts
  $("radar").innerHTML = radarSVG(r.axes);
  $("catbars").innerHTML = barChart(topN(r.proba, 5), true);
  $("compbars").innerHTML = competitorBars(r.competitors);
  drawScatter(r.segment.segment);

  // insights
  const seg = r.segment;
  $("seg_label").textContent = seg.label;
  $("seg_sub").textContent =
    `~${seg.size} customers · avg age ${Math.round(seg.profile.age)} · ` +
    `income ₹${Math.round(seg.profile.income_k)}k · spend ${Math.round(seg.profile.spend_score)}/100`;
  $("weakness").innerHTML =
    `🛠 Biggest weakness: <u>${r.weakest_axis}</u> ` +
    `(${Math.round(r.axes[r.weakest_axis])}/100) — focus there.`;

  // competitor table
  $("comptable").innerHTML = competitorTable(r.competitors);

  $("results").scrollIntoView({ behavior: "smooth", block: "start" });
}

// ---- helpers -------------------------------------------------------------
function topN(proba, n) {
  return Object.entries(proba).sort((a, b) => b[1] - a[1]).slice(0, n);
}

function animateNumber(el, target) {
  let cur = 0;
  const step = Math.max(1, target / 24);
  clearInterval(el._t);
  el._t = setInterval(() => {
    cur += step;
    if (cur >= target) { cur = target; clearInterval(el._t); }
    el.textContent = Math.round(cur);
  }, 18);
}

function barChart(entries, highlightTop) {
  const max = Math.max(...entries.map((e) => e[1]), 0.001);
  return entries.map(([name, val], i) => {
    const pct = (val / max) * 100;
    const color = highlightTop && i === 0 ? "#c4b5fd" : "#e5e7eb";
    return `<div class="bar-row"><span class="bar-name">${escapeHtml(name)}</span>
      <span class="bar-track"><span class="bar-fill" style="width:${pct}%;background:${color}"></span></span>
      <span class="bar-val">${Math.round(val * 100)}%</span></div>`;
  }).join("");
}

function competitorBars(comps) {
  if (!comps || !comps.length) return `<p>No similar ideas found.</p>`;
  return comps.map((c, i) => {
    const pct = c.similarity * 100;
    const color = c.outcome === "Success" ? "#22c55e" : "#fb7185";
    return `<div class="bar-row"><span class="bar-name">#${i + 1} ${c.category}</span>
      <span class="bar-track"><span class="bar-fill" style="width:${pct}%;background:${color}"></span></span>
      <span class="bar-val">${Math.round(pct)}%</span></div>`;
  }).join("");
}

function competitorTable(comps) {
  if (!comps || !comps.length) return `<p>No close matches — this idea looks fairly unique.</p>`;
  const rows = comps.map((c) => {
    const cls = c.outcome === "Success" ? "win" : "fail";
    return `<tr><td>${c.category}</td>
      <td><span class="pill-out ${cls}">${c.outcome}</span></td>
      <td>${Math.round(c.similarity * 100)}%</td>
      <td>${escapeHtml(c.idea)}</td></tr>`;
  }).join("");
  return `<table class="comp"><tr><th>Category</th><th>Outcome</th><th>Sim</th><th>Idea</th></tr>${rows}</table>`;
}

// ---- SVG radar -----------------------------------------------------------
function radarSVG(axes) {
  const labels = Object.keys(axes);
  const vals = labels.map((k) => axes[k]);
  const n = labels.length;
  const cx = 160, cy = 150, R = 100;
  const ang = (i) => -Math.PI / 2 + (i * 2 * Math.PI) / n;
  const pt = (i, r) => [cx + r * Math.cos(ang(i)), cy + r * Math.sin(ang(i))];

  let grid = "";
  [25, 50, 75, 100].forEach((ring) => {
    const p = labels.map((_, i) => pt(i, (ring / 100) * R).join(",")).join(" ");
    grid += `<polygon points="${p}" fill="none" stroke="#d4d4d4" stroke-width="1.5"/>`;
  });
  let spokes = "";
  labels.forEach((_, i) => {
    const [x, y] = pt(i, R);
    spokes += `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#d4d4d4" stroke-width="1.5"/>`;
  });
  const dataPts = vals.map((v, i) => pt(i, (v / 100) * R).join(",")).join(" ");
  let dots = "";
  vals.forEach((v, i) => {
    const [x, y] = pt(i, (v / 100) * R);
    dots += `<circle cx="${x}" cy="${y}" r="4" fill="${INK}"/>`;
  });
  let text = "";
  labels.forEach((lab, i) => {
    const [x, y] = pt(i, R + 22);
    const anchor = Math.abs(x - cx) < 10 ? "middle" : x > cx ? "start" : "end";
    text += `<text x="${x}" y="${y}" text-anchor="${anchor}" dominant-baseline="middle"
      font-size="12" font-weight="800" fill="${INK}">${lab}</text>`;
  });

  return `<svg viewBox="0 0 320 300" role="img" aria-label="Radar chart of the five scoring axes">
    ${grid}${spokes}
    <polygon points="${dataPts}" fill="#c4b5fd" fill-opacity="0.55" stroke="${INK}" stroke-width="2.5"/>
    ${dots}${text}</svg>`;
}

// ---- SVG scatter ---------------------------------------------------------
function drawScatter(target) {
  if (!SEGMENTS) { $("scatter").innerHTML = "<p>Loading…</p>"; return; }
  const W = 320, H = 240, pad = 34;
  const pts = SEGMENTS.points;
  const xs = pts.map((p) => p.income), ys = pts.map((p) => p.spend);
  const xmin = Math.min(...xs), xmax = Math.max(...xs);
  const ymin = Math.min(...ys), ymax = Math.max(...ys);
  const sx = (v) => pad + ((v - xmin) / (xmax - xmin || 1)) * (W - pad - 12);
  const sy = (v) => H - pad - ((v - ymin) / (ymax - ymin || 1)) * (H - pad - 12);

  const circles = pts.map((p) => {
    const isT = p.segment === target;
    const c = SEG_COLORS[p.segment % SEG_COLORS.length];
    return `<circle cx="${sx(p.income).toFixed(1)}" cy="${sy(p.spend).toFixed(1)}"
      r="${isT ? 6 : 3.2}" fill="${c}" fill-opacity="${isT ? 1 : 0.4}"
      stroke="${isT ? INK : "none"}" stroke-width="${isT ? 1.6 : 0}"/>`;
  }).join("");

  $("scatter").innerHTML = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Customer segments scatter plot">
    <line x1="${pad}" y1="${H - pad}" x2="${W - 6}" y2="${H - pad}" stroke="${INK}" stroke-width="2"/>
    <line x1="${pad}" y1="12" x2="${pad}" y2="${H - pad}" stroke="${INK}" stroke-width="2"/>
    <text x="${W / 2}" y="${H - 6}" text-anchor="middle" font-size="11" font-weight="700">Income (k)</text>
    <text x="12" y="${H / 2}" text-anchor="middle" font-size="11" font-weight="700"
      transform="rotate(-90 12 ${H / 2})">Spend</text>
    ${circles}</svg>`;

  // legend
  const desc = SEGMENTS.descriptions || {};
  $("scatter_leg").innerHTML = Object.keys(desc).map((k) => {
    const isT = +k === target;
    return `<span><i style="background:${SEG_COLORS[k % SEG_COLORS.length]}"></i>
      Seg ${k}${isT ? " ★ (target)" : ""}</span>`;
  }).join("");
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"]/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}
